# Generated by Django 5.0.6 on 2025-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'booked'), ('payment pending', 'payment pending'), ('reject', 'reject'), ('paid', 'paid'), ('approved', 'approved')], default='payment pending', max_length=50),
        ),
    ]
