# Generated by Django 5.0.6 on 2025-02-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='HealthAssistant_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='no_of_people',
        ),
    ]
