# Generated by Django 5.0.6 on 2025-02-11 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_vendorrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthAssistant',
        ),
    ]
