# Generated by Django 5.0.6 on 2025-02-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_healthassistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='package',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='package',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='package',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='package',
            name='no_of_night',
        ),
        migrations.RemoveField(
            model_name='package',
            name='source',
        ),
    ]
