# Generated by Django 5.0.6 on 2025-02-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_package_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='review',
        ),
    ]
