# Generated by Django 5.0.6 on 2025-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting', 'waiting'), ('approved', 'approved'), ('picked', 'picked'), ('reject', 'reject'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
    ]
