# Generated by Django 5.0.6 on 2025-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
