# Generated by Django 5.0.6 on 2025-02-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_booking_address_booking_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pin',
        ),
    ]
