# Generated by Django 5.0.6 on 2025-02-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_booking_address_remove_booking_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='Address', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='pin',
            field=models.CharField(default='673579', max_length=6),
        ),
    ]
