# Generated by Django 5.0.6 on 2025-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_booking_address_booking_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='phone', max_length=6),
        ),
    ]
