# Generated by Django 5.0.6 on 2025-02-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='phone', max_length=10),
        ),
    ]
