# Generated by Django 5.0.6 on 2025-02-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='img1',
            field=models.FileField(default='Image', upload_to='package'),
        ),
    ]
