# Generated by Django 5.0.6 on 2025-02-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_package_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.CharField(default='Icon', max_length=50),
        ),
    ]
