# Generated by Django 5.0.6 on 2025-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_package_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='icon',
            field=models.CharField(default='Icon', max_length=50),
        ),
    ]
