# Generated by Django 5.0.6 on 2025-02-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_booking_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='icon',
        ),
    ]
